build:
    environment:
        php:
            version: 5.6
    tests:
        override:
            - phpcs-run --standard=.cs/cs_ruleset.xml --extensions=php src
            - phpcs-run --standard=.cs/cs_ruleset.xml --extensions=php tests
            -
                command: ./vendor/bin/phpunit --coverage-clover=collection.clover
                coverage:
                    file: collection.clover
                    format: php-clover

checks:
    php:
        duplication: false
        unused_variables: false
        no_exit: false

filter:
    excluded_paths:
        - vendor/*
        - .idea
        - .codeclimate.yml
        - .scrutinizer.yml


