sudo: false
language: php
cache:
  directories:
  - $HOME/.composer/cache
  - vendor
matrix:
  fast_finish: true
  include:
  - php: 5.6
  - php: 7
  - php: hhvm
    env:
    - PHP_HHVM=true
  allow_failures:
  - php: hhvm
before_install:
- if [[ $PHP_HHVM != 'true' ]]; then phpenv config-rm xdebug.ini; fi
- composer self-update
install:
- travis_retry composer install --no-interaction
- composer info -i
script:
- php vendor/bin/phpcs --standard=.cs/cs_ruleset.xml --extensions=php src/
- php vendor/bin/phpcs --standard=.cs/cs_ruleset.xml --extensions=php tests
- php vendor/bin/phpunit
#after_success:
#- if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./scripts/travis_deploy_doc.bash ; fi
notifications:
  email: false
