sudo: false
language: php
cache:
  directories:
  - $HOME/.composer/cache
matrix:
  fast_finish: true
  include:
  - php: 5.6
  - php: 7
  - php: 7.1
  env:
  - DEBUG_COLLECTION_CLASS="Novactive\Collection\Collection"
  - DEBUG_COLLECTION_CLASS="Novactive\Collection\Debug\Collection"
  - DEBUG_COLLECTION_CLASS="Novactive\Tests\Perfs\ArrayMethodCollection"
  - DEBUG_COLLECTION_CLASS="Novactive\Tests\Perfs\ForeachMethodCollection"
  allow_failures:
  - env: DEBUG_COLLECTION_CLASS="Novactive\Tests\Perfs\ArrayMethodCollection"
  - env: DEBUG_COLLECTION_CLASS="Novactive\Tests\Perfs\ForeachMethodCollection"

before_install:
- phpenv config-rm xdebug.ini
- composer self-update
- openssl aes-256-cbc -K $encrypted_31ceb3c17ab3_key -iv $encrypted_31ceb3c17ab3_iv -in tests/Perfs/imgur.credentials.php.enc -out tests/Perfs/imgur.credentials.php -d
install:
- travis_retry composer install --no-interaction
- composer info -i
script:
- php vendor/bin/phpcs --standard=.cs/cs_ruleset.xml --extensions=php src/
- php vendor/bin/phpcs --standard=.cs/cs_ruleset.xml --extensions=php tests
- php vendor/bin/phpunit
after_success:
- bash tests/Perfs/run.bash 1 1
#- if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./scripts/travis_deploy_doc.bash ; fi
notifications:
  email: false
